### ISSUE TITLE
While GinUI installed Windows context menu is not working

### ISSUE THREAD

**Issue by JiriVanek** [G-Node/GinUI#92] opened 2019-01-23 12:55 UTC
After installation of GinUI is Context menu in Windows incredibly slow, after disabling GinShellExtensionClass works like a charm again.
Windows 10 Professional 64-bit.
Same behavior on two different computers.

**Comment by achilleas-k** [comment] 2019-01-23 12:56
That seems bad. Do you mean that it takes very long for the context menu to appear when right clicking on a file?
Does it happen everywhere, or only inside GIN repositories?

**Comment by JiriVanek** [comment] 2019-01-23 13:02
Exactly. it tooks several minutes to menu opens... And it occurs on any file / folder or desktop even outside GIN repositories.

**Comment by achilleas-k** [comment] 2019-01-23 13:03
Ok. Definitely bad. Thanks for reporting.

**Comment by achilleas-k** [comment] 2019-01-24 15:10
Issue was caused by GIN service being in a faulty state. A restart fixed it and we haven't managed to reproduce. Closing

**Closed by achilleas-k** 2019-01-24 15:10 UTC
Labels: bug
